name: Generate Binaries
on:
  release:
    types: [created]

jobs:
    ubuntu:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                fetch-depth: 0

            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                python-version: '3.11'

            - name: Install dependencies
              run: |
                    sudo apt-get update -y && \
                    sudo apt-get install -y build-essential git ninja-build nasm gcc-multilib
                    sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)" llvm 18

            - name: Build
              run: |
                ./build.sh dist

            - name: Upload binaries
              uses: skx/github-action-publish-binaries@release-1.3
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                args: '.cutekit/dist/*'